name: Lint Commit Messages
on: [pull_request]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
